id: balll
name: balll
name[zh]: 检测器 307967
version: 1.0.0
author: TZJ
icon: app.png
desc: nb
exclude:
  - __pycache__
  - build
  - dist
  - .gitignore
files:
  - app.png
  - app.yaml
  - main.py
  - model_307967.cvimodel
  - model_307967.mud
  - report.json
