name: Cppcheck Analysis

on:
  push:
    paths:
      - 'Core/Src/**'
      - 'Core/Inc/**'
  pull_request:
    paths:
      - 'Core/Src/**'
      - 'Core/Inc/**'

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            --enable=warning,style
            --suppress=missingIncludeSystem
            --error-exitcode=1
            --max-configs=1
            -i Drivers
            -i Middlewares
            ./Core
